
# This file was generated by the SOM Compiler.
# FileName: maprog.psc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter EMITPSC: 1.10

/*
 * 
 * 
 *   Module Name: MAPROG (Multiple Argument Program)
 * 
 *   Simple OS/2 Work Place Shell Program
 * 
 */


/*
 * Include the .sc file
 */
#include "maprog.sc"

class: MAProg;

