
/*
 * This file was generated by the SOM Compiler.
 * FileName: maprog.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter EMITH: 1.11
 */

/*
 * 
 * 
 * 
 *   Module Name: MAPROG (Multiple Argument Program)
 * 
 *   Simple OS/2 Work Place Shell Program
 * 
 */


#ifndef maprog_h
#define maprog_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef MAProg
#define MAProg SOMAny
#endif
#include "wppgm.h"

/*
 * Passthru lines: File: "C.h", "after"
 */



#define MAProg_MajorVersion 1
#define MAProg_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define MAProgNewClass maprogc
#pragma linkage(maprogc, system)
#define MAProgClassData maprogd
#define MAProgCClassData maprogx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define MAProg_classObj MAProgClassData.classObject
#define _MAProg MAProg_classObj

/*
 * New and Renew macros for MAProg
 */
#define _MAProgNew() (_somNew(MAProgClassData.classObject))
#define MAProgNew() \
	( MAProgClassData.classObject \
		? _MAProgNew() \
		: ( MAProgNewClass(MAProg_MajorVersion, MAProg_MinorVersion), _MAProgNew() ) )
#define MAProgRenew(buf) \
	( _somRenew(MAProgClassData.classObject, buf) )

/*
 * Override method: wpDrop
 */
#define MAProg_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK MAProgNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(MAProgNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct MAProgClassDataStructure {
	SOMAny *classObject;
} MAProgClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct MAProgCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} MAProgCClassData;

#endif       /* maprog_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: maprog.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter EMITH: 1.11
 */

#ifndef maprog_mh
#define maprog_mh


/*
 * Define the class name as an object type
 */
#ifndef M_MAProg
#define M_MAProg SOMAny
#endif

#define M_MAProg_MajorVersion 1
#define M_MAProg_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_MAProgNewClass maprogc
#pragma linkage(maprogc, system)
#define M_MAProgClassData maprogd
#define M_MAProgCClassData maprogx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_MAProg_classObj M_MAProgClassData.classObject
#define _M_MAProg M_MAProg_classObj

/*
 * New and Renew macros for M_MAProg
 */
#define _M_MAProgNew() (_somNew(M_MAProgClassData.classObject))
#define M_MAProgNew() \
	( M_MAProgClassData.classObject \
		? _M_MAProgNew() \
		: ( M_MAProgNewClass(M_MAProg_MajorVersion, M_MAProg_MinorVersion), _M_MAProgNew() ) )
#define M_MAProgRenew(buf) \
	( _somRenew(M_MAProgClassData.classObject, buf) )

/*
 * Override method: wpclsQueryTitle
 */
#define M_MAProg_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_MAProg_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE    SOMLINK somTP_M_MAProg_clsQueryModuleHandle(M_MAProg *somSelf);
#pragma linkage(somTP_M_MAProg_clsQueryModuleHandle, system)
typedef somTP_M_MAProg_clsQueryModuleHandle *somTD_M_MAProg_clsQueryModuleHandle;
#define somMD_M_MAProg_clsQueryModuleHandle "----"
#define M_MAProg_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_MAProg, clsQueryModuleHandle) \
	(somSelf))
#define _clsQueryModuleHandle M_MAProg_clsQueryModuleHandle

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_MAProgNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_MAProgNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_MAProgClassDataStructure {
	SOMAny *classObject;
	somMToken clsQueryModuleHandle;
} M_MAProgClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_MAProgCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_MAProgCClassData;

#endif       /* maprog_h */
